"""ImprovementSuggestion model for LLM-generated prompt improvements."""

import uuid
from datetime import UTC, datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:
    from app.models.agent import Agent
    from app.models.prompt_version import PromptVersion
    from app.models.user import User


class ImprovementSuggestion(Base):
    """Queue of LLM-generated prompt improvement suggestions.

    Stores suggestions generated by analyzing call performance,
    allowing human review before activating new prompt versions.
    """

    __tablename__ = "improvement_suggestions"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    agent_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("agents.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    source_version_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("prompt_versions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # The suggested improvement
    suggested_prompt: Mapped[str] = mapped_column(Text, nullable=False)
    suggested_greeting: Mapped[str | None] = mapped_column(Text, nullable=True)
    mutation_type: Mapped[str] = mapped_column(
        String(50), nullable=False
    )  # warmer_tone, objection_handling, more_concise, etc.

    # LLM analysis that led to this suggestion
    analysis_summary: Mapped[str] = mapped_column(Text, nullable=False)
    expected_improvement: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Queue status: pending, approved, rejected, expired
    status: Mapped[str] = mapped_column(String(20), default="pending", nullable=False, index=True)
    reviewed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    reviewed_by_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True
    )
    rejection_reason: Mapped[str | None] = mapped_column(Text, nullable=True)

    # If approved, link to created version
    created_version_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("prompt_versions.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(UTC), nullable=False
    )

    # Relationships
    agent: Mapped["Agent"] = relationship("Agent")
    source_version: Mapped["PromptVersion"] = relationship(
        "PromptVersion", foreign_keys=[source_version_id]
    )
    created_version: Mapped["PromptVersion | None"] = relationship(
        "PromptVersion", foreign_keys=[created_version_id]
    )
    reviewed_by: Mapped["User | None"] = relationship("User")

    def __repr__(self) -> str:
        return f"<ImprovementSuggestion(id={self.id}, type={self.mutation_type})>"
