"""Shared idempotency primitives for outbound effects, webhooks, and workers.

The helpers in this module cover three recurring backend patterns:

* derive stable UUID keys for outbound side effects that persist on ``messages``;
* apply those keys to provider requests (HTTP headers / Telnyx client_state);
* derive and claim text keys for webhook deliveries and worker retry/DLQ items.

The outbound UUID namespace is intentionally the legacy
``thetribunal.outbound.v1`` namespace so in-flight retries generated by older
worker code keep deduping after this shared module is introduced.
"""

from __future__ import annotations

import base64
import uuid
from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.redis import get_redis
from app.models.conversation import Message, MessageStatus

OUTBOUND_IDEMPOTENCY_NAMESPACE = uuid.uuid5(uuid.NAMESPACE_DNS, "thetribunal.outbound.v1")
DEFAULT_IDEMPOTENCY_HEADER = "X-Idempotency-Key"
DEFAULT_WEBHOOK_IDEMPOTENCY_TTL_SECONDS = 7 * 24 * 60 * 60

RedisGetter = Callable[[], Awaitable[Any]]


@dataclass(frozen=True, slots=True)
class MessageIdempotencyState:
    """Resolved state for a potentially idempotent outbound ``Message`` send."""

    effective_key: uuid.UUID
    existing_message: Message | None
    should_skip: bool


@dataclass(frozen=True, slots=True)
class RedisIdempotencyClaim:
    """Result of atomically claiming a Redis-backed idempotency key."""

    key: str
    claimed: bool
    reason: str | None = None


def derive_outbound_key(scope: str, *parts: object) -> uuid.UUID:
    """Return a deterministic UUID5 for an outbound side effect.

    ``scope`` is a short domain-owned namespace such as ``"reminder"`` or
    ``"voice_campaign_call"``. ``parts`` are stringified in order. The exact
    ``scope:part:...`` body preserves the original telephony helper contract.
    """
    if not scope:
        msg = "idempotency scope must be non-empty"
        raise ValueError(msg)
    body = scope + ":" + ":".join(str(part) for part in parts)
    return uuid.uuid5(OUTBOUND_IDEMPOTENCY_NAMESPACE, body)


def derive_worker_retry_key(scope: str, *parts: object) -> str:
    """Return a stable text key for ``RetryableWorker`` item/DLQ dedupe."""
    if not scope:
        msg = "worker retry scope must be non-empty"
        raise ValueError(msg)
    if not parts:
        return scope
    return scope + ":" + ":".join(str(part) for part in parts)


def webhook_key_prefix(provider: str) -> str:
    """Return the canonical Redis key prefix for provider webhook deliveries."""
    provider_name = provider.strip().lower()
    if not provider_name:
        msg = "webhook provider must be non-empty"
        raise ValueError(msg)
    return f"{provider_name}:webhook:"


def derive_webhook_delivery_key(provider: str, *parts: object) -> str | None:
    """Return ``<provider>:webhook:<parts>`` or ``None`` if any part is missing.

    Webhook callers should fail open on ``None`` rather than dropping legitimate
    traffic whose provider omitted delivery identity fields.
    """
    if not parts:
        return None
    normalized = [str(part) for part in parts if part is not None]
    if len(normalized) != len(parts) or any(part == "" for part in normalized):
        return None
    return webhook_key_prefix(provider) + ":".join(normalized)


def idempotency_headers(
    key: uuid.UUID | None,
    *,
    header_name: str = DEFAULT_IDEMPOTENCY_HEADER,
) -> dict[str, str]:
    """Return provider request headers carrying ``key`` when present."""
    if key is None:
        return {}
    return {header_name: str(key)}


def encode_client_state(key: uuid.UUID) -> str:
    """Return Telnyx Call Control ``client_state`` for an idempotency key."""
    return base64.b64encode(str(key).encode("ascii")).decode("ascii")


def is_message_send_applied(message: Message) -> bool:
    """Return True when an existing message row means the side effect ran.

    A ``queued`` row is resumable: the prior attempt persisted the local row but
    may have crashed before reaching the provider. Any other status is treated
    as already applied so retries return the existing row without another send.
    """
    return message.status not in {MessageStatus.QUEUED, MessageStatus.QUEUED.value}


async def find_message_by_idempotency_key(
    db: AsyncSession,
    idempotency_key: uuid.UUID | None,
) -> Message | None:
    """Return the ``Message`` row for ``idempotency_key`` if one exists."""
    if idempotency_key is None:
        return None
    result = await db.execute(select(Message).where(Message.idempotency_key == idempotency_key))
    return result.scalar_one_or_none()


async def resolve_message_idempotency(
    db: AsyncSession,
    idempotency_key: uuid.UUID | None,
) -> MessageIdempotencyState:
    """Resolve the effective key and any existing row for an outbound send."""
    effective_key = idempotency_key or uuid.uuid4()
    existing = await find_message_by_idempotency_key(db, idempotency_key)
    return MessageIdempotencyState(
        effective_key=effective_key,
        existing_message=existing,
        should_skip=existing is not None and is_message_send_applied(existing),
    )


async def claim_redis_idempotency_key(
    key: str,
    *,
    ttl_seconds: int = DEFAULT_WEBHOOK_IDEMPOTENCY_TTL_SECONDS,
    log: Any,
    redis_getter: RedisGetter = get_redis,
    failure_event: str = "idempotency_redis_unavailable",
) -> RedisIdempotencyClaim:
    """Atomically claim ``key`` with ``SET NX EX`` and fail open on Redis errors."""
    try:
        client = await redis_getter()
        was_set = await client.set(key, "1", nx=True, ex=ttl_seconds)
    except Exception as exc:
        log.warning(failure_event, key=key, error=str(exc))
        return RedisIdempotencyClaim(key=key, claimed=True, reason="redis_unavailable")

    if was_set:
        return RedisIdempotencyClaim(key=key, claimed=True, reason="claimed")
    return RedisIdempotencyClaim(key=key, claimed=False, reason="duplicate")
