"""SQLAlchemy base model."""

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# Standard SQLAlchemy/Alembic naming convention for constraints and indexes.
# Ensures autogenerated migrations produce stable, predictable constraint names
# (e.g. `ix_users_email`, `fk_orders_user_id_users`) instead of database-assigned
# defaults that vary between engines and Alembic revisions.
#
# NOTE: This convention applies to NEW constraints/indexes only. Existing
# constraints in the database keep their current names — we are not renaming
# them in a migration. Over time, as constraints are dropped/recreated through
# normal schema evolution, the database will converge on this convention.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for all SQLAlchemy models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
