"""add_offers_table_and_campaign_offer_id

Revision ID: 03876dc32a6c
Revises: e6c0ca7dd25e
Create Date: 2025-12-31 18:05:53.815733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03876dc32a6c'
down_revision: str | None = "e6c0ca7dd25e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.String(length=50), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_workspace_id'), 'offers', ['workspace_id'], unique=False)
    op.add_column('campaigns', sa.Column('offer_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_campaigns_offer_id'), 'campaigns', ['offer_id'], unique=False)
    op.create_foreign_key(None, 'campaigns', 'offers', ['offer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_index(op.f('ix_campaigns_offer_id'), table_name='campaigns')
    op.drop_column('campaigns', 'offer_id')
    op.drop_index(op.f('ix_offers_workspace_id'), table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
