"""add recurring job templates

Revision ID: 05ee4fe87849
Revises: 46afccc11055
Create Date: 2026-06-29 21:02:36.283621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05ee4fe87849'
down_revision: Union[str, None] = '46afccc11055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_job_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('service_location_id', sa.UUID(), nullable=True),
    sa.Column('crew_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.Integer(), server_default='1', nullable=False),
    sa.Column('duration_minutes', sa.Integer(), server_default='60', nullable=False),
    sa.Column('generate_days_ahead', sa.Integer(), server_default='14', nullable=False),
    sa.Column('default_technician_ids', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_recurring_job_templates_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_recurring_job_templates_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], name=op.f('fk_recurring_job_templates_crew_id_crews'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_location_id'], ['service_locations.id'], name=op.f('fk_recurring_job_templates_service_location_id_service_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_recurring_job_templates_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurring_job_templates'))
    )
    op.create_index(op.f('ix_recurring_job_templates_contact_id'), 'recurring_job_templates', ['contact_id'], unique=False)
    op.create_index(op.f('ix_recurring_job_templates_crew_id'), 'recurring_job_templates', ['crew_id'], unique=False)
    op.create_index('ix_recurring_job_templates_due', 'recurring_job_templates', ['is_active', 'next_run_at'], unique=False)
    op.create_index(op.f('ix_recurring_job_templates_service_location_id'), 'recurring_job_templates', ['service_location_id'], unique=False)
    op.create_index('ix_recurring_job_templates_workspace_active', 'recurring_job_templates', ['workspace_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_recurring_job_templates_workspace_id'), 'recurring_job_templates', ['workspace_id'], unique=False)
    op.add_column('field_service_jobs', sa.Column('recurring_template_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_field_service_jobs_recurring_template_id'), 'field_service_jobs', ['recurring_template_id'], unique=False)
    op.create_foreign_key(op.f('fk_field_service_jobs_recurring_template_id_recurring_job_templates'), 'field_service_jobs', 'recurring_job_templates', ['recurring_template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_field_service_jobs_recurring_template_id_recurring_job_templates'), 'field_service_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_field_service_jobs_recurring_template_id'), table_name='field_service_jobs')
    op.drop_column('field_service_jobs', 'recurring_template_id')
    op.drop_index(op.f('ix_recurring_job_templates_workspace_id'), table_name='recurring_job_templates')
    op.drop_index('ix_recurring_job_templates_workspace_active', table_name='recurring_job_templates')
    op.drop_index(op.f('ix_recurring_job_templates_service_location_id'), table_name='recurring_job_templates')
    op.drop_index('ix_recurring_job_templates_due', table_name='recurring_job_templates')
    op.drop_index(op.f('ix_recurring_job_templates_crew_id'), table_name='recurring_job_templates')
    op.drop_index(op.f('ix_recurring_job_templates_contact_id'), table_name='recurring_job_templates')
    op.drop_table('recurring_job_templates')
    # ### end Alembic commands ###
