"""add invoice public_token for customer invoice page

Backs the public ``/p/invoices/{token}`` page so a customer can view and pay an
invoice without an account. Nullable because existing invoices (and every draft)
have no token: it is allocated lazily on first send, so a draft link can never
resolve. Unique so a token addresses exactly one invoice; indexed for O(1)
anonymous lookup. Mirrors ``quotes.public_token``.

Additive and reversible -- no backfill, no data rewrite.

Revision ID: 0f445fca20c5
Revises: 42bcb2ed6509
Create Date: 2026-07-30 21:48:02.074572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f445fca20c5'
down_revision: Union[str, None] = '42bcb2ed6509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('public_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_invoices_public_token'), 'invoices', ['public_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_public_token'), table_name='invoices')
    op.drop_column('invoices', 'public_token')
    # ### end Alembic commands ###
