"""Pre-booking campaigns: selling next season's work during the dry months.

Revision ID: 42bcb2ed6509
Revises: 8d7ca9999bfc
Create Date: 2026-07-30 16:31:13.540140

Seasonal *pricing* already existed; seasonal *demand planning* did not. These two
tables let one ordinary SMS/email campaign sell work months ahead of the season
it will be delivered in, at a discount, in exchange for a deposit.

Adds:

- ``prebooking_campaign_configs`` — the offer hung off one campaign: which months
  the work happens (start/end month plus the year the window *starts* in, so a
  season that wraps the new year needs no second year column), the booking
  incentive, the deposit, and the ``slot_cap`` that keeps the crew calendar
  honest. ``campaign_id`` is UNIQUE: one offer per campaign, which is what makes
  the ORM side a safe one-to-one and gives the cap a single row to lock.
- ``prebooking_reservations`` — one contact's claim on a slot, from issued quote
  through paid deposit. ``quote_id`` and ``job_id`` are SET NULL so deleting
  either leaves the booking history readable rather than cascading a customer's
  reservation out of existence.

The load-bearing constraint is ``uq_prebooking_reservations_active_contact``: a
partial UNIQUE over ``(campaign_id, contact_id)`` WHERE the status is ``held`` or
``confirmed``. It makes "one live claim per customer per campaign" a database
guarantee — an eager customer clicking twice cannot eat two slots — while leaving
``released``/``cancelled`` history in place so a genuine second attempt still
works.

Both enum columns are ``VARCHAR(20)`` (``native_enum=False``) rather than Postgres
ENUM types, matching ``referral_partners.partner_type`` and
``neighbor_outreach_entries.status``: a future status needs no ``ALTER TYPE``.

No customer PII is copied here. The contact is referenced by id and the address
stays on the (encrypted) service location the converted job points at.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42bcb2ed6509'
down_revision: Union[str, None] = '8d7ca9999bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prebooking_campaign_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('service_season_start_month', sa.Integer(), nullable=False),
    sa.Column('service_season_end_month', sa.Integer(), nullable=False),
    sa.Column('service_season_year', sa.Integer(), nullable=False),
    sa.Column('service_description', sa.String(length=200), nullable=False),
    sa.Column('incentive_type', sa.Enum('percentage', 'fixed', name='prebookingamounttype', native_enum=False, length=20), nullable=False),
    sa.Column('incentive_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deposit_type', sa.Enum('percentage', 'fixed', name='prebookingamounttype', native_enum=False, length=20), nullable=False),
    sa.Column('deposit_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('slot_cap', sa.Integer(), nullable=False),
    sa.Column('hold_hours', sa.Integer(), server_default='72', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_prebooking_campaign_configs_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_prebooking_campaign_configs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prebooking_campaign_configs'))
    )
    op.create_index(op.f('ix_prebooking_campaign_configs_campaign_id'), 'prebooking_campaign_configs', ['campaign_id'], unique=True)
    op.create_index(op.f('ix_prebooking_campaign_configs_workspace_id'), 'prebooking_campaign_configs', ['workspace_id'], unique=False)
    op.create_table('prebooking_reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('held', 'confirmed', 'released', 'cancelled', name='prebookingreservationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('target_start_date', sa.DATE(), nullable=False),
    sa.Column('target_end_date', sa.DATE(), nullable=False),
    sa.Column('quoted_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('incentive_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('held_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_prebooking_reservations_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['config_id'], ['prebooking_campaign_configs.id'], name=op.f('fk_prebooking_reservations_config_id_prebooking_campaign_configs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_prebooking_reservations_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['field_service_jobs.id'], name=op.f('fk_prebooking_reservations_job_id_field_service_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_prebooking_reservations_quote_id_quotes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_prebooking_reservations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prebooking_reservations'))
    )
    op.create_index(op.f('ix_prebooking_reservations_campaign_id'), 'prebooking_reservations', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_prebooking_reservations_config_id'), 'prebooking_reservations', ['config_id'], unique=False)
    op.create_index('ix_prebooking_reservations_config_status', 'prebooking_reservations', ['config_id', 'status'], unique=False)
    op.create_index(op.f('ix_prebooking_reservations_contact_id'), 'prebooking_reservations', ['contact_id'], unique=False)
    op.create_index(op.f('ix_prebooking_reservations_hold_expires_at'), 'prebooking_reservations', ['hold_expires_at'], unique=False)
    op.create_index(op.f('ix_prebooking_reservations_job_id'), 'prebooking_reservations', ['job_id'], unique=False)
    op.create_index(op.f('ix_prebooking_reservations_quote_id'), 'prebooking_reservations', ['quote_id'], unique=False)
    op.create_index(op.f('ix_prebooking_reservations_workspace_id'), 'prebooking_reservations', ['workspace_id'], unique=False)
    op.create_index('ix_prebooking_reservations_workspace_status', 'prebooking_reservations', ['workspace_id', 'status'], unique=False)
    op.create_index('uq_prebooking_reservations_active_contact', 'prebooking_reservations', ['campaign_id', 'contact_id'], unique=True, postgresql_where=sa.text("status IN ('held', 'confirmed')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_prebooking_reservations_active_contact', table_name='prebooking_reservations', postgresql_where=sa.text("status IN ('held', 'confirmed')"))
    op.drop_index('ix_prebooking_reservations_workspace_status', table_name='prebooking_reservations')
    op.drop_index(op.f('ix_prebooking_reservations_workspace_id'), table_name='prebooking_reservations')
    op.drop_index(op.f('ix_prebooking_reservations_quote_id'), table_name='prebooking_reservations')
    op.drop_index(op.f('ix_prebooking_reservations_job_id'), table_name='prebooking_reservations')
    op.drop_index(op.f('ix_prebooking_reservations_hold_expires_at'), table_name='prebooking_reservations')
    op.drop_index(op.f('ix_prebooking_reservations_contact_id'), table_name='prebooking_reservations')
    op.drop_index('ix_prebooking_reservations_config_status', table_name='prebooking_reservations')
    op.drop_index(op.f('ix_prebooking_reservations_config_id'), table_name='prebooking_reservations')
    op.drop_index(op.f('ix_prebooking_reservations_campaign_id'), table_name='prebooking_reservations')
    op.drop_table('prebooking_reservations')
    op.drop_index(op.f('ix_prebooking_campaign_configs_workspace_id'), table_name='prebooking_campaign_configs')
    op.drop_index(op.f('ix_prebooking_campaign_configs_campaign_id'), table_name='prebooking_campaign_configs')
    op.drop_table('prebooking_campaign_configs')
    # ### end Alembic commands ###
