"""add job time entries, expenses, and job invoice link

Revision ID: 46afccc11055
Revises: 5acb1b941277
Create Date: 2026-06-29 18:04:15.990128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46afccc11055'
down_revision: Union[str, None] = '5acb1b941277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('incurred_on', sa.DATE(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_job_expenses_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['field_service_jobs.id'], name=op.f('fk_job_expenses_job_id_field_service_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_job_expenses_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_expenses'))
    )
    op.create_index(op.f('ix_job_expenses_job_id'), 'job_expenses', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_expenses_workspace_id'), 'job_expenses', ['workspace_id'], unique=False)
    op.create_index('ix_job_expenses_workspace_job', 'job_expenses', ['workspace_id', 'job_id'], unique=False)
    op.create_table('job_time_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('technician_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_job_time_entries_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['field_service_jobs.id'], name=op.f('fk_job_time_entries_job_id_field_service_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], name=op.f('fk_job_time_entries_technician_id_technicians'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_job_time_entries_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_time_entries'))
    )
    op.create_index(op.f('ix_job_time_entries_job_id'), 'job_time_entries', ['job_id'], unique=False)
    op.create_index('ix_job_time_entries_job_open', 'job_time_entries', ['job_id', 'ended_at'], unique=False)
    op.create_index(op.f('ix_job_time_entries_technician_id'), 'job_time_entries', ['technician_id'], unique=False)
    op.create_index(op.f('ix_job_time_entries_workspace_id'), 'job_time_entries', ['workspace_id'], unique=False)
    op.create_index('ix_job_time_entries_workspace_job', 'job_time_entries', ['workspace_id', 'job_id'], unique=False)
    op.add_column('field_service_jobs', sa.Column('invoice_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_field_service_jobs_invoice_id'), 'field_service_jobs', ['invoice_id'], unique=False)
    op.create_foreign_key(op.f('fk_field_service_jobs_invoice_id_invoices'), 'field_service_jobs', 'invoices', ['invoice_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_field_service_jobs_invoice_id_invoices'), 'field_service_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_field_service_jobs_invoice_id'), table_name='field_service_jobs')
    op.drop_column('field_service_jobs', 'invoice_id')
    op.drop_index('ix_job_time_entries_workspace_job', table_name='job_time_entries')
    op.drop_index(op.f('ix_job_time_entries_workspace_id'), table_name='job_time_entries')
    op.drop_index(op.f('ix_job_time_entries_technician_id'), table_name='job_time_entries')
    op.drop_index('ix_job_time_entries_job_open', table_name='job_time_entries')
    op.drop_index(op.f('ix_job_time_entries_job_id'), table_name='job_time_entries')
    op.drop_table('job_time_entries')
    op.drop_index('ix_job_expenses_workspace_job', table_name='job_expenses')
    op.drop_index(op.f('ix_job_expenses_workspace_id'), table_name='job_expenses')
    op.drop_index(op.f('ix_job_expenses_job_id'), table_name='job_expenses')
    op.drop_table('job_expenses')
    # ### end Alembic commands ###
