"""add comparison per_ft_override

Revision ID: 5aca94c46ae6
Revises: c2297c21b99d
Create Date: 2026-07-14 19:14:13.185168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aca94c46ae6'
down_revision: Union[str, None] = 'c2297c21b99d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roofline_comparisons', sa.Column('per_ft_override', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roofline_comparisons', 'per_ft_override')
    # ### end Alembic commands ###
