"""add catalog_items price book

Revision ID: 5acb1b941277
Revises: 630aea148e30
Create Date: 2026-06-29 15:01:02.055033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5acb1b941277'
down_revision: Union[str, None] = '630aea148e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('kind', sa.Enum('service', 'product', name='catalog_item_kind'), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('taxable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_catalog_items_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_catalog_items_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_items'))
    )
    op.create_index(op.f('ix_catalog_items_created_by_id'), 'catalog_items', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_catalog_items_is_active'), 'catalog_items', ['is_active'], unique=False)
    op.create_index(op.f('ix_catalog_items_kind'), 'catalog_items', ['kind'], unique=False)
    op.create_index(op.f('ix_catalog_items_workspace_id'), 'catalog_items', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_items_workspace_id'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_kind'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_is_active'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_created_by_id'), table_name='catalog_items')
    op.drop_table('catalog_items')
    # Drop the named enum type so the migration is fully reversible.
    sa.Enum(name='catalog_item_kind').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
