"""card on file

Lands the storage for saving a customer's card once and charging it later while
they are not present:

* ``contacts.stripe_customer_id`` — the opaque ``cus_...`` handle, reused across
  all of a contact's cards. Nullable and indexed; not PII.
* ``contact_payment_methods`` — the ``pm_...`` handle plus display-only metadata
  (brand / last4 / expiry) and the ``mandate_*`` consent record Stripe requires
  us to retain. **No column can hold a card number.** The partial unique index
  ``uq_contact_payment_methods_default`` enforces at most one default *active*
  card per contact.
* ``card_charge_attempts`` — every off-session attempt, succeeded or not, keyed
  by a unique ``idempotency_key`` that is also handed to Stripe so one key means
  one PaymentIntent and one row.

Purely additive: no existing row or behavior changes, and ``downgrade()`` drops
only what this migration created.

Revision ID: 62f4596028a4
Revises: c2e043d6bb65
Create Date: 2026-08-05 19:41:32.361969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f4596028a4'
down_revision: Union[str, None] = 'c2e043d6bb65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_payment_methods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('stripe_payment_method_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=20), nullable=True),
    sa.Column('last4', sa.String(length=4), nullable=True),
    sa.Column('exp_month', sa.Integer(), nullable=True),
    sa.Column('exp_year', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('mandate_text_version', sa.String(length=50), nullable=False),
    sa.Column('mandate_accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mandate_ip', sa.String(length=45), nullable=True),
    sa.Column('mandate_user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_contact_payment_methods_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_contact_payment_methods_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_payment_methods')),
    sa.UniqueConstraint('stripe_payment_method_id', name=op.f('uq_contact_payment_methods_stripe_payment_method_id'))
    )
    op.create_index(op.f('ix_contact_payment_methods_contact_id'), 'contact_payment_methods', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contact_payment_methods_status'), 'contact_payment_methods', ['status'], unique=False)
    op.create_index(op.f('ix_contact_payment_methods_stripe_customer_id'), 'contact_payment_methods', ['stripe_customer_id'], unique=False)
    op.create_index('ix_contact_payment_methods_workspace_contact', 'contact_payment_methods', ['workspace_id', 'contact_id'], unique=False)
    op.create_index(op.f('ix_contact_payment_methods_workspace_id'), 'contact_payment_methods', ['workspace_id'], unique=False)
    op.create_index('uq_contact_payment_methods_default', 'contact_payment_methods', ['contact_id'], unique=True, postgresql_where=sa.text("is_default AND status = 'active'"))
    op.create_table('card_charge_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_method_id', sa.UUID(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decline_code', sa.String(length=64), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_card_charge_attempts_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_card_charge_attempts_invoice_id_invoices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['contact_payment_methods.id'], name=op.f('fk_card_charge_attempts_payment_method_id_contact_payment_methods'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_card_charge_attempts_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_charge_attempts')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_card_charge_attempts_idempotency_key'))
    )
    op.create_index('ix_card_charge_attempts_contact_created', 'card_charge_attempts', ['contact_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_card_charge_attempts_contact_id'), 'card_charge_attempts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_card_charge_attempts_invoice_id'), 'card_charge_attempts', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_card_charge_attempts_payment_method_id'), 'card_charge_attempts', ['payment_method_id'], unique=False)
    op.create_index(op.f('ix_card_charge_attempts_status'), 'card_charge_attempts', ['status'], unique=False)
    op.create_index(op.f('ix_card_charge_attempts_stripe_payment_intent_id'), 'card_charge_attempts', ['stripe_payment_intent_id'], unique=False)
    op.create_index(op.f('ix_card_charge_attempts_trigger'), 'card_charge_attempts', ['trigger'], unique=False)
    op.create_index('ix_card_charge_attempts_workspace_created', 'card_charge_attempts', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_card_charge_attempts_workspace_id'), 'card_charge_attempts', ['workspace_id'], unique=False)
    op.add_column('contacts', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_contacts_stripe_customer_id'), 'contacts', ['stripe_customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_stripe_customer_id'), table_name='contacts')
    op.drop_column('contacts', 'stripe_customer_id')
    op.drop_index(op.f('ix_card_charge_attempts_workspace_id'), table_name='card_charge_attempts')
    op.drop_index('ix_card_charge_attempts_workspace_created', table_name='card_charge_attempts')
    op.drop_index(op.f('ix_card_charge_attempts_trigger'), table_name='card_charge_attempts')
    op.drop_index(op.f('ix_card_charge_attempts_stripe_payment_intent_id'), table_name='card_charge_attempts')
    op.drop_index(op.f('ix_card_charge_attempts_status'), table_name='card_charge_attempts')
    op.drop_index(op.f('ix_card_charge_attempts_payment_method_id'), table_name='card_charge_attempts')
    op.drop_index(op.f('ix_card_charge_attempts_invoice_id'), table_name='card_charge_attempts')
    op.drop_index(op.f('ix_card_charge_attempts_contact_id'), table_name='card_charge_attempts')
    op.drop_index('ix_card_charge_attempts_contact_created', table_name='card_charge_attempts')
    op.drop_table('card_charge_attempts')
    op.drop_index('uq_contact_payment_methods_default', table_name='contact_payment_methods', postgresql_where=sa.text("is_default AND status = 'active'"))
    op.drop_index(op.f('ix_contact_payment_methods_workspace_id'), table_name='contact_payment_methods')
    op.drop_index('ix_contact_payment_methods_workspace_contact', table_name='contact_payment_methods')
    op.drop_index(op.f('ix_contact_payment_methods_stripe_customer_id'), table_name='contact_payment_methods')
    op.drop_index(op.f('ix_contact_payment_methods_status'), table_name='contact_payment_methods')
    op.drop_index(op.f('ix_contact_payment_methods_contact_id'), table_name='contact_payment_methods')
    op.drop_table('contact_payment_methods')
    # ### end Alembic commands ###
