"""add quotes and quote line items

Revision ID: 630aea148e30
Revises: b8b15c8633c6
Create Date: 2026-06-29 14:08:43.852448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '630aea148e30'
down_revision: Union[str, None] = 'b8b15c8633c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=True),
    sa.Column('service_location_id', sa.UUID(), nullable=True),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'approved', 'declined', 'expired', name='quote_status'), nullable=False),
    sa.Column('issue_date', sa.DATE(), nullable=True),
    sa.Column('expiry_date', sa.DATE(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('converted_job_id', sa.UUID(), nullable=True),
    sa.Column('converted_invoice_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_quotes_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['converted_invoice_id'], ['invoices.id'], name=op.f('fk_quotes_converted_invoice_id_invoices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['converted_job_id'], ['field_service_jobs.id'], name=op.f('fk_quotes_converted_job_id_field_service_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_quotes_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_quotes_opportunity_id_opportunities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_location_id'], ['service_locations.id'], name=op.f('fk_quotes_service_location_id_service_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_quotes_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotes')),
    sa.UniqueConstraint('workspace_id', 'number', name='uq_quotes_workspace_number')
    )
    op.create_index(op.f('ix_quotes_contact_id'), 'quotes', ['contact_id'], unique=False)
    op.create_index(op.f('ix_quotes_converted_invoice_id'), 'quotes', ['converted_invoice_id'], unique=False)
    op.create_index(op.f('ix_quotes_converted_job_id'), 'quotes', ['converted_job_id'], unique=False)
    op.create_index(op.f('ix_quotes_created_by_id'), 'quotes', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_quotes_opportunity_id'), 'quotes', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_quotes_service_location_id'), 'quotes', ['service_location_id'], unique=False)
    op.create_index(op.f('ix_quotes_status'), 'quotes', ['status'], unique=False)
    op.create_index(op.f('ix_quotes_workspace_id'), 'quotes', ['workspace_id'], unique=False)
    op.create_table('quote_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_quote_line_items_quote_id_quotes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_line_items'))
    )
    op.create_index(op.f('ix_quote_line_items_quote_id'), 'quote_line_items', ['quote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_line_items_quote_id'), table_name='quote_line_items')
    op.drop_table('quote_line_items')
    op.drop_index(op.f('ix_quotes_workspace_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_status'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_service_location_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_opportunity_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_created_by_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_converted_job_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_converted_invoice_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_contact_id'), table_name='quotes')
    op.drop_table('quotes')
    # Drop the named enum type so the migration is fully reversible.
    sa.Enum(name='quote_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
