"""phone number lead source attribution

Revision ID: 794de67ae8c8
Revises: 7dc9d61efed7
Create Date: 2026-07-29 16:57:06.987984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '794de67ae8c8'
down_revision: Union[str, None] = '7dc9d61efed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_numbers', sa.Column('lead_source_id', sa.UUID(), nullable=True))
    op.add_column('phone_numbers', sa.Column('lead_source_campaign_id', sa.UUID(), nullable=True))
    op.add_column('phone_numbers', sa.Column('tracking_label', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_phone_numbers_lead_source_campaign_id'), 'phone_numbers', ['lead_source_campaign_id'], unique=False)
    op.create_index(op.f('ix_phone_numbers_lead_source_id'), 'phone_numbers', ['lead_source_id'], unique=False)
    op.create_foreign_key(op.f('fk_phone_numbers_lead_source_id_lead_sources'), 'phone_numbers', 'lead_sources', ['lead_source_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_phone_numbers_lead_source_campaign_id_lead_source_campaigns'), 'phone_numbers', 'lead_source_campaigns', ['lead_source_campaign_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_phone_numbers_lead_source_campaign_id_lead_source_campaigns'), 'phone_numbers', type_='foreignkey')
    op.drop_constraint(op.f('fk_phone_numbers_lead_source_id_lead_sources'), 'phone_numbers', type_='foreignkey')
    op.drop_index(op.f('ix_phone_numbers_lead_source_id'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_lead_source_campaign_id'), table_name='phone_numbers')
    op.drop_column('phone_numbers', 'tracking_label')
    op.drop_column('phone_numbers', 'lead_source_campaign_id')
    op.drop_column('phone_numbers', 'lead_source_id')
    # ### end Alembic commands ###
