"""add comparison selected_package

Revision ID: 7c5a23b17a86
Revises: 99e23f6b89ef
Create Date: 2026-07-15 09:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7c5a23b17a86'
down_revision: Union[str, None] = '99e23f6b89ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roofline_comparisons', sa.Column('selected_package', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roofline_comparisons', 'selected_package')
    # ### end Alembic commands ###
