"""Add contact_id to roofline_comparisons

Revision ID: 99e23f6b89ef
Revises: f7a2c9d1e3b5
Create Date: 2026-07-15 08:48:25.666363

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99e23f6b89ef"
down_revision: Union[str, None] = "f7a2c9d1e3b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("roofline_comparisons", sa.Column("contact_id", sa.BigInteger(), nullable=True))
    op.create_index(
        op.f("ix_roofline_comparisons_contact_id"),
        "roofline_comparisons",
        ["contact_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_roofline_comparisons_contact_id_contacts"),
        "roofline_comparisons",
        "contacts",
        ["contact_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_roofline_comparisons_contact_id_contacts"),
        "roofline_comparisons",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_roofline_comparisons_contact_id"), table_name="roofline_comparisons")
    op.drop_column("roofline_comparisons", "contact_id")
    # ### end Alembic commands ###
