"""add comparison christmas_per_ft_override

Revision ID: b35dc15658d3
Revises: 5aca94c46ae6
Create Date: 2026-07-14 19:34:49.172097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b35dc15658d3'
down_revision: Union[str, None] = '5aca94c46ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roofline_comparisons', sa.Column('christmas_per_ft_override', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roofline_comparisons', 'christmas_per_ft_override')
    # ### end Alembic commands ###
