"""add roofline_comparisons

Revision ID: c2297c21b99d
Revises: 21019f8d527d
Create Date: 2026-07-14 18:24:47.610794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2297c21b99d'
down_revision: Union[str, None] = '21019f8d527d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roofline_comparisons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('public_token', sa.String(length=64), nullable=False),
    sa.Column('feet', sa.Float(), nullable=False),
    sa.Column('channels', sa.Integer(), nullable=False),
    sa.Column('takedown', sa.Boolean(), nullable=False),
    sa.Column('storage', sa.Boolean(), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_roofline_comparisons_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_roofline_comparisons_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roofline_comparisons'))
    )
    op.create_index(op.f('ix_roofline_comparisons_created_by_id'), 'roofline_comparisons', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_roofline_comparisons_public_token'), 'roofline_comparisons', ['public_token'], unique=True)
    op.create_index(op.f('ix_roofline_comparisons_workspace_id'), 'roofline_comparisons', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roofline_comparisons_workspace_id'), table_name='roofline_comparisons')
    op.drop_index(op.f('ix_roofline_comparisons_public_token'), table_name='roofline_comparisons')
    op.drop_index(op.f('ix_roofline_comparisons_created_by_id'), table_name='roofline_comparisons')
    op.drop_table('roofline_comparisons')
    # ### end Alembic commands ###
