"""contact email opt out

Revision ID: c8432d3de92b
Revises: ca399d6e0b02
Create Date: 2026-08-12 19:08:37.489205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8432d3de92b'
down_revision: Union[str, None] = 'ca399d6e0b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('email_opted_out_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('contacts', sa.Column('email_opt_out_source', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_contacts_email_opted_out_at'), 'contacts', ['email_opted_out_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_email_opted_out_at'), table_name='contacts')
    op.drop_column('contacts', 'email_opt_out_source')
    op.drop_column('contacts', 'email_opted_out_at')
    # ### end Alembic commands ###
