"""contact card setup tokens

The short-lived link a customer opens to type their own card in. Unlike the
invoice and proposal share tokens — permanent, because a customer may bookmark
them — this one expires (72h, ``CARD_SETUP_TOKEN_TTL_HOURS``) and is single-use
via ``used_at``: a permanent "enter your card here" URL is a standing phishing
asset, and burning the token on use is also what stops the unauthenticated
endpoint behind it from being an unbounded generator of billable Stripe objects.

Purely additive.

Revision ID: c85ad29f4648
Revises: 62f4596028a4
Create Date: 2026-08-05 19:50:49.750853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85ad29f4648'
down_revision: Union[str, None] = '62f4596028a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_card_setup_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_contact_card_setup_tokens_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_contact_card_setup_tokens_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_contact_card_setup_tokens_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_card_setup_tokens'))
    )
    op.create_index('ix_contact_card_setup_tokens_contact_created', 'contact_card_setup_tokens', ['contact_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_contact_card_setup_tokens_contact_id'), 'contact_card_setup_tokens', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contact_card_setup_tokens_token'), 'contact_card_setup_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_contact_card_setup_tokens_workspace_id'), 'contact_card_setup_tokens', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_card_setup_tokens_workspace_id'), table_name='contact_card_setup_tokens')
    op.drop_index(op.f('ix_contact_card_setup_tokens_token'), table_name='contact_card_setup_tokens')
    op.drop_index(op.f('ix_contact_card_setup_tokens_contact_id'), table_name='contact_card_setup_tokens')
    op.drop_index('ix_contact_card_setup_tokens_contact_created', table_name='contact_card_setup_tokens')
    op.drop_table('contact_card_setup_tokens')
    # ### end Alembic commands ###
