"""automation execution resume state

Revision ID: ca399d6e0b02
Revises: 3c451b655d90
Create Date: 2026-08-12 18:52:59.676157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca399d6e0b02'
down_revision: Union[str, None] = '3c451b655d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automation_executions', sa.Column('step_index', sa.Integer(), server_default='0', nullable=False))
    op.add_column('automation_executions', sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('automation_executions', sa.Column('resume_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('automation_executions', 'resume_count')
    op.drop_column('automation_executions', 'context')
    op.drop_column('automation_executions', 'step_index')
    # ### end Alembic commands ###
