"""add comparison christmas_items

Revision ID: d4945a5167e0
Revises: b35dc15658d3
Create Date: 2026-07-14 20:00:27.871856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4945a5167e0'
down_revision: Union[str, None] = 'b35dc15658d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roofline_comparisons', sa.Column('christmas_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roofline_comparisons', 'christmas_items')
    # ### end Alembic commands ###
