"""add_voice_campaign_fields

Revision ID: e5fe47013c85
Revises: b1c2d3e4f5a6
Create Date: 2026-01-03 11:01:14.117817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5fe47013c85'
down_revision: str | None = "b1c2d3e4f5a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # CampaignContact call tracking fields
    op.add_column('campaign_contacts', sa.Column('call_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('campaign_contacts', sa.Column('last_call_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaign_contacts', sa.Column('last_call_status', sa.String(length=50), nullable=True))
    op.add_column('campaign_contacts', sa.Column('call_duration_seconds', sa.Integer(), nullable=True))
    op.add_column('campaign_contacts', sa.Column('call_message_id', sa.UUID(), nullable=True))
    op.add_column('campaign_contacts', sa.Column('sms_fallback_sent', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('campaign_contacts', sa.Column('sms_fallback_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaign_contacts', sa.Column('sms_fallback_message_id', sa.UUID(), nullable=True))

    # Campaign type and voice settings
    op.add_column('campaigns', sa.Column('campaign_type', sa.String(length=50), nullable=False, server_default='sms'))
    op.add_column('campaigns', sa.Column('voice_agent_id', sa.UUID(), nullable=True))
    op.add_column('campaigns', sa.Column('voice_connection_id', sa.String(length=255), nullable=True))
    op.add_column('campaigns', sa.Column('enable_machine_detection', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('campaigns', sa.Column('max_call_duration_seconds', sa.Integer(), nullable=False, server_default='120'))
    op.add_column('campaigns', sa.Column('calls_per_minute', sa.Integer(), nullable=False, server_default='5'))

    # SMS fallback settings
    op.add_column('campaigns', sa.Column('sms_fallback_enabled', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('campaigns', sa.Column('sms_fallback_template', sa.Text(), nullable=True))
    op.add_column('campaigns', sa.Column('sms_fallback_use_ai', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('campaigns', sa.Column('sms_fallback_agent_id', sa.UUID(), nullable=True))

    # Voice campaign statistics
    op.add_column('campaigns', sa.Column('calls_attempted', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('campaigns', sa.Column('calls_answered', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('campaigns', sa.Column('calls_no_answer', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('campaigns', sa.Column('calls_busy', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('campaigns', sa.Column('calls_voicemail', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('campaigns', sa.Column('sms_fallbacks_sent', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('campaigns', 'initial_message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_campaigns_campaign_type'), 'campaigns', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_campaigns_sms_fallback_agent_id'), 'campaigns', ['sms_fallback_agent_id'], unique=False)
    op.create_index(op.f('ix_campaigns_voice_agent_id'), 'campaigns', ['voice_agent_id'], unique=False)
    op.create_foreign_key(None, 'campaigns', 'agents', ['sms_fallback_agent_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'campaigns', 'agents', ['voice_agent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_index(op.f('ix_campaigns_voice_agent_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_sms_fallback_agent_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_campaign_type'), table_name='campaigns')
    op.alter_column('campaigns', 'initial_message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('campaigns', 'sms_fallbacks_sent')
    op.drop_column('campaigns', 'calls_voicemail')
    op.drop_column('campaigns', 'calls_busy')
    op.drop_column('campaigns', 'calls_no_answer')
    op.drop_column('campaigns', 'calls_answered')
    op.drop_column('campaigns', 'calls_attempted')
    op.drop_column('campaigns', 'sms_fallback_agent_id')
    op.drop_column('campaigns', 'sms_fallback_use_ai')
    op.drop_column('campaigns', 'sms_fallback_template')
    op.drop_column('campaigns', 'sms_fallback_enabled')
    op.drop_column('campaigns', 'calls_per_minute')
    op.drop_column('campaigns', 'max_call_duration_seconds')
    op.drop_column('campaigns', 'enable_machine_detection')
    op.drop_column('campaigns', 'voice_connection_id')
    op.drop_column('campaigns', 'voice_agent_id')
    op.drop_column('campaigns', 'campaign_type')
    op.drop_column('campaign_contacts', 'sms_fallback_message_id')
    op.drop_column('campaign_contacts', 'sms_fallback_sent_at')
    op.drop_column('campaign_contacts', 'sms_fallback_sent')
    op.drop_column('campaign_contacts', 'call_message_id')
    op.drop_column('campaign_contacts', 'call_duration_seconds')
    op.drop_column('campaign_contacts', 'last_call_status')
    op.drop_column('campaign_contacts', 'last_call_at')
    op.drop_column('campaign_contacts', 'call_attempts')
    # ### end Alembic commands ###
