"""add service locations crews technicians

Revision ID: f26eea725a62
Revises: f9a1b2c3d4e6
Create Date: 2026-06-26 19:35:59.237112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f26eea725a62'
down_revision: Union[str, None] = 'f9a1b2c3d4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('color', sa.String(length=7), server_default='#6366f1', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_crews_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crews')),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_crews_workspace_name')
    )
    op.create_index('ix_crews_workspace_active', 'crews', ['workspace_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_crews_workspace_id'), 'crews', ['workspace_id'], unique=False)
    op.create_table('technicians',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('crew_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('color', sa.String(length=7), server_default='#0ea5e9', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], name=op.f('fk_technicians_crew_id_crews'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_technicians_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_technicians_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technicians'))
    )
    op.create_index(op.f('ix_technicians_crew_id'), 'technicians', ['crew_id'], unique=False)
    op.create_index(op.f('ix_technicians_user_id'), 'technicians', ['user_id'], unique=False)
    op.create_index('ix_technicians_workspace_active', 'technicians', ['workspace_id', 'is_active'], unique=False)
    op.create_index('ix_technicians_workspace_crew', 'technicians', ['workspace_id', 'crew_id'], unique=False)
    op.create_index(op.f('ix_technicians_workspace_id'), 'technicians', ['workspace_id'], unique=False)
    op.create_table('service_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    # EncryptedString columns store Fernet ciphertext as TEXT at the DB level.
    sa.Column('address_line1', sa.Text(), nullable=True),
    sa.Column('address_line2', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=2), server_default='US', nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('access_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_service_locations_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_service_locations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_locations'))
    )
    op.create_index(op.f('ix_service_locations_contact_id'), 'service_locations', ['contact_id'], unique=False)
    op.create_index('ix_service_locations_workspace_active', 'service_locations', ['workspace_id', 'is_active'], unique=False)
    op.create_index('ix_service_locations_workspace_contact', 'service_locations', ['workspace_id', 'contact_id'], unique=False)
    op.create_index(op.f('ix_service_locations_workspace_id'), 'service_locations', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_locations_workspace_id'), table_name='service_locations')
    op.drop_index('ix_service_locations_workspace_contact', table_name='service_locations')
    op.drop_index('ix_service_locations_workspace_active', table_name='service_locations')
    op.drop_index(op.f('ix_service_locations_contact_id'), table_name='service_locations')
    op.drop_table('service_locations')
    op.drop_index(op.f('ix_technicians_workspace_id'), table_name='technicians')
    op.drop_index('ix_technicians_workspace_crew', table_name='technicians')
    op.drop_index('ix_technicians_workspace_active', table_name='technicians')
    op.drop_index(op.f('ix_technicians_user_id'), table_name='technicians')
    op.drop_index(op.f('ix_technicians_crew_id'), table_name='technicians')
    op.drop_table('technicians')
    op.drop_index(op.f('ix_crews_workspace_id'), table_name='crews')
    op.drop_index('ix_crews_workspace_active', table_name='crews')
    op.drop_table('crews')
    # ### end Alembic commands ###
