"""Schemas for recurring job templates (maintenance contracts).

A template repeats a job on a schedule. ``next_run_at`` is the cursor for the
next occurrence to generate: on create it is the first occurrence's start time;
the recurring-job worker advances it by ``interval`` × ``frequency`` after each
materialization. Status/lifecycle fields are maintained server-side.
"""

import uuid
from datetime import datetime

from pydantic import BaseModel, Field

from app.models.recurring_job import RecurrenceFrequency


class RecurringJobTemplateBase(BaseModel):
    """Fields shared by create and (optionally) update."""

    title: str = Field(..., min_length=1, max_length=200)
    description: str | None = Field(None, max_length=5000)
    frequency: RecurrenceFrequency
    interval: int = Field(1, ge=1, le=52, description="Repeat every N periods")
    duration_minutes: int = Field(
        60, ge=1, le=10080, description="Length of each generated job's window"
    )
    generate_days_ahead: int = Field(
        14, ge=0, le=365, description="Materialize the job this many days before its start"
    )
    service_location_id: uuid.UUID | None = Field(None, description="Job site")
    crew_id: uuid.UUID | None = Field(None, description="Default dispatch lane/crew")
    default_technician_ids: list[uuid.UUID] = Field(
        default_factory=list, description="Technicians to tag onto each generated job"
    )


class RecurringJobTemplateCreate(RecurringJobTemplateBase):
    """Create a recurring job template."""

    contact_id: int = Field(..., description="Customer this contract serves")
    next_run_at: datetime = Field(..., description="Start time of the first occurrence to generate")
    is_active: bool = True


class RecurringJobTemplateUpdate(BaseModel):
    """Partial update for a recurring job template."""

    title: str | None = Field(None, min_length=1, max_length=200)
    description: str | None = Field(None, max_length=5000)
    frequency: RecurrenceFrequency | None = None
    interval: int | None = Field(None, ge=1, le=52)
    duration_minutes: int | None = Field(None, ge=1, le=10080)
    generate_days_ahead: int | None = Field(None, ge=0, le=365)
    service_location_id: uuid.UUID | None = None
    crew_id: uuid.UUID | None = None
    default_technician_ids: list[uuid.UUID] | None = None
    next_run_at: datetime | None = None
    is_active: bool | None = None


class RecurringJobTemplateResponse(BaseModel):
    """A recurring job template with its scheduling cursor."""

    id: uuid.UUID
    workspace_id: uuid.UUID
    contact_id: int
    service_location_id: uuid.UUID | None
    crew_id: uuid.UUID | None
    title: str
    description: str | None
    frequency: RecurrenceFrequency
    interval: int
    duration_minutes: int
    generate_days_ahead: int
    default_technician_ids: list[uuid.UUID]
    next_run_at: datetime
    last_run_at: datetime | None
    is_active: bool
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}


class RecurringJobTemplateListResponse(BaseModel):
    """List of recurring job templates."""

    items: list[RecurringJobTemplateResponse]
    total: int


class RecurringJobRunResponse(BaseModel):
    """Result of force-generating the next occurrence(s) for a template."""

    created: int = Field(..., description="Number of jobs generated by this run")
    template: RecurringJobTemplateResponse
